// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4311.subsystems;

import java.util.concurrent.TimeUnit;

import org.usfirst.frc4311.RobotMap;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

public class RobotSystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController rightFront = RobotMap.robotDriveRightFront;
    SpeedController leftFront = RobotMap.robotDriveLeftFront;
    SpeedController rightRear = RobotMap.robotDriveRightRear;
    SpeedController leftRear = RobotMap.robotDriveLeftRear;
    edu.wpi.first.wpilibj.RobotDrive drive = RobotMap.robotDriveDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public void moveForward(double speed){
    	rightFront.set(-speed);
    	rightRear.set(-speed);
    	leftFront.set(speed);
    	leftRear.set(speed);
    }
    
    public void turnLeft(double speed){
    	rightFront.set(speed);
    	rightRear.set(speed);
    	leftFront.set(speed);
    	leftRear.set(speed);
    }
    
    public void turnRight(double speed){
    	rightFront.set(-speed);
    	rightRear.set(-speed);
    	leftFront.set(speed);
    	leftRear.set(speed);
    }
    
    public void stop(){
    	rightFront.set(0);
    	rightRear.set(0);
    	leftFront.set(0);
    	leftRear.set(0);
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

